## Check Mistral OCR + pixtral-12b-latest

In [2]:
from mistral_client import MistralFormExtractor

In [3]:
IMAGE_PATH = "../../samples/input/jml.png"

# # View Image
# from PIL import Image
# Image.open(IMAGE_PATH)

# View OCR Result
mistral_extractor = MistralFormExtractor()
parsed_form, ocr_text = mistral_extractor.structured_ocr(IMAGE_PATH)
print(parsed_form)

✅ Mistral client initialized
Running Mistral OCR...
Parsing with Mistral LLM...
Upload_ID='AJ-20251113-152907-6006f778' Extracted_AT='2025-11-13T15:29:07.930827' Aircraft_Model='Airbus A320' Registration_Number='9M-XX1' Departure_Airport='KUL' Arrival_Airport='SIN' Crew=4 Fuel='12k' Load=150 Defect_Message='WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'

In [4]:
import json
from typing import Dict, Any, List, Optional, Tuple

# convert AircraftJourneyFormExtractor output to json model
parsed_form = parsed_form.model_dump_json(indent=2)
print(parsed_form)

{
  "Upload_ID": "AJ-20251113-152907-6006f778",
  "Extracted_AT": "2025-11-13T15:29:07.930827",
  "Aircraft_Model": "Airbus A320",
  "Registration_Number": "9M-XX1",
  "Departure_Airport": "KUL",
  "Arrival_Airport": "SIN",
  "Crew": 4,
  "Fuel": "12k",
  "Load": 150,
  "Defect_Message": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE."
}

In [5]:
# multiple json records
from glob import glob
import os

IMAGES = glob("../../samples/input/*.png")
IMAGES

['../../samples/input/jml1.png',
 '../../samples/input/jml3.png',
 '../../samples/input/jml2.png',
 '../../samples/input/jml.png']

In [6]:
IMAGES = [
    '../../samples/input/jml1.png',
    '../../samples/input/jml3.png',
    '../../samples/input/jml2.png',
    '../../samples/input/jml.png'
    ]

In [7]:
parse_results = []
for img_path in IMAGES:
    result, _ = mistral_extractor.structured_ocr(img_path)
    # print(result.model_dump_json(indent=2))
    parse_results.append(result.model_dump())  # Use model_dump() directly

# Now you can convert to DataFrame
import pandas as pd
df = pd.DataFrame(parse_results)
display(df)

Running Mistral OCR...
Parsing with Mistral LLM...
Running Mistral OCR...
Parsing with Mistral LLM...
Running Mistral OCR...
Parsing with Mistral LLM...
Running Mistral OCR...
Parsing with Mistral LLM...

,Upload_ID,Extracted_AT,Aircraft_Model,Registration_Number,Departure_Airport,Arrival_Airport,Crew,Fuel,Load,Defect_Message
0,AJ-20251113-152924-0f39b460,2025-11-13T15:29:24.663312,None,None,None,None,NaN,None,NaN,None
1,AJ-20251113-152956-b66e012f,2025-11-13T15:29:56.366923,None,None,None,None,NaN,None,NaN,None
2,AJ-20251113-152958-932c434b,2025-11-13T15:29:58.997230,None,9A-AGG,LHR,CDG,NaN,123,NaN,None
3,AJ-20251113-153003-f4982e98,2025-11-13T15:30:03.401685,Airbus A320,9M-XX1,KUL,SIN,4.0,12k,150.0,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...

In [8]:
parse_results

[{'Upload_ID': 'AJ-20251113-152924-0f39b460',
  'Extracted_AT': '2025-11-13T15:29:24.663312',
  'Aircraft_Model': None,
  'Registration_Number': None,
  'Departure_Airport': None,
  'Arrival_Airport': None,
  'Crew': None,
  'Fuel': None,
  'Load': None,
  'Defect_Message': None},
 {'Upload_ID': 'AJ-20251113-152956-b66e012f',
  'Extracted_AT': '2025-11-13T15:29:56.366923',
  'Aircraft_Model': None,
  'Registration_Number': None,
  'Departure_Airport': None,
  'Arrival_Airport': None,
  'Crew': None,
  'Fuel': None,
  'Load': None,
  'Defect_Message': None},
 {'Upload_ID': 'AJ-20251113-152958-932c434b',
  'Extracted_AT': '2025-11-13T15:29:58.997230',
  'Aircraft_Model': None,
  'Registration_Number': '9A-AGG',
  'Departure_Airport': 'LHR',
  'Arrival_Airport': 'CDG',
  'Crew': None,
  'Fuel': '123',
  'Load': None,
  'Defect_Message': None},
 {'Upload_ID': 'AJ-20251113-153003-f4982e98',
  'Extracted_AT': '2025-11-13T15:30:03.401685',
  'Aircraft_Model': 'Airbus A320',
  'Registration_Number': '9M-XX1',
  'Departure_Airport': 'KUL',
  'Arrival_Airport': 'SIN',
  'Crew': 4,
  'Fuel': '12k',
  'Load': 150,
  'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'}]

In [9]:
df

,Upload_ID,Extracted_AT,Aircraft_Model,Registration_Number,Departure_Airport,Arrival_Airport,Crew,Fuel,Load,Defect_Message
0,AJ-20251113-152924-0f39b460,2025-11-13T15:29:24.663312,None,None,None,None,NaN,None,NaN,None
1,AJ-20251113-152956-b66e012f,2025-11-13T15:29:56.366923,None,None,None,None,NaN,None,NaN,None
2,AJ-20251113-152958-932c434b,2025-11-13T15:29:58.997230,None,9A-AGG,LHR,CDG,NaN,123,NaN,None
3,AJ-20251113-153003-f4982e98,2025-11-13T15:30:03.401685,Airbus A320,9M-XX1,KUL,SIN,4.0,12k,150.0,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...

In [10]:
result.model_dump()

{'Upload_ID': 'AJ-20251113-153003-f4982e98',
 'Extracted_AT': '2025-11-13T15:30:03.401685',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12k',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'}

## Check json upload to S3

In [11]:
EXTRACTED_PREFIX = "ocr_results/extracted"
EDITED_PREFIX = "ocr_results/edited"
RESULTS_PREFIX = "ocr_results/results"
UPLOAD_PREFIX = "uploads"

In [12]:
IMAGE_PATH

'../../samples/input/jml.png'

In [13]:
# @app.post("/extract/")
# create json file upload function to S3
file_path = IMAGE_PATH

# Run extraction
print("🔍 Running OCR extraction...")
result, _ = mistral_extractor.structured_ocr(str(file_path))

# Convert to dict
result_dict = json.loads(result.json())
result_dict

🔍 Running OCR extraction...
Running Mistral OCR...
Parsing with Mistral LLM...

/var/folders/yz/01283wk557g3r_2q2cbpz5dr0000gn/T/ipykernel_8768/497420407.py:10: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  result_dict = json.loads(result.json())

{'Upload_ID': 'AJ-20251113-153009-56ab04c4',
 'Extracted_AT': '2025-11-13T15:30:09.130996',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12k',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'}

In [14]:
result.model_dump()

{'Upload_ID': 'AJ-20251113-153009-56ab04c4',
 'Extracted_AT': '2025-11-13T15:30:09.130996',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12k',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'}

In [32]:
df.to_csv("ocr_results.csv", index=False)

In [15]:
from aws_utils import upload_json_to_s3_folder

# @app.post("/save-extracted/")
data = result.model_dump() # convert class type to dict
upload_id = data.get("Upload_ID", "unknown")
version = data.get("version", "extracted")

print(f"Upload ID: {upload_id}, Version: {version}")
output_filename = f"{upload_id}_extracted.json"

s3_uri = None
try:
    s3_key = f"{EXTRACTED_PREFIX}/{upload_id}.json"
    print(f"☁️ Uploading to S3: {s3_key}")
    s3_uri = upload_json_to_s3_folder(json.dumps(data), s3_key=s3_key)
    print(f"✅ S3 upload successful: {s3_uri}")
except Exception as s3_error:
    print(f"⚠️ S3 upload failed (non-critical): {s3_error}")
    s3_uri = f"S3 upload failed: {str(s3_error)}"
    # pass

/Users/jusnaini/Documents/MyProject/PERSONAL/ADE_interview/libenv/lib/python3.9/site-packages/boto3/compat.py:84: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

Upload ID: AJ-20251113-153009-56ab04c4, Version: extracted
☁️ Uploading to S3: ocr_results/extracted/AJ-20251113-153009-56ab04c4.json
✅ S3 upload successful: s3://aircraftform-extractor-bucket/ocr_results/extracted/AJ-20251113-153009-56ab04c4.json

In [16]:
res_json_dump = result.model_dump()
display(type(res_json_dump))

json.dumps(res_json_dump)

dict

'{"Upload_ID": "AJ-20251113-153009-56ab04c4", "Extracted_AT": "2025-11-13T15:30:09.130996", "Aircraft_Model": "Airbus A320", "Registration_Number": "9M-XX1", "Departure_Airport": "KUL", "Arrival_Airport": "SIN", "Crew": 4, "Fuel": "12k", "Load": 150, "Defect_Message": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE."}'

In [17]:
type(json.dumps(res_json_dump))

str

In [18]:
res_json_load = json.loads(result.json())
display(type(res_json_load))

json.dumps(res_json_load)

/var/folders/yz/01283wk557g3r_2q2cbpz5dr0000gn/T/ipykernel_8768/674909493.py:1: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  res_json_load = json.loads(result.json())

dict

'{"Upload_ID": "AJ-20251113-153009-56ab04c4", "Extracted_AT": "2025-11-13T15:30:09.130996", "Aircraft_Model": "Airbus A320", "Registration_Number": "9M-XX1", "Departure_Airport": "KUL", "Arrival_Airport": "SIN", "Crew": 4, "Fuel": "12k", "Load": 150, "Defect_Message": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE."}'

In [19]:
pd.DataFrame([res_json_load])

,Upload_ID,Extracted_AT,Aircraft_Model,Registration_Number,Departure_Airport,Arrival_Airport,Crew,Fuel,Load,Defect_Message
0,AJ-20251113-153009-56ab04c4,2025-11-13T15:30:09.130996,Airbus A320,9M-XX1,KUL,SIN,4,12k,150,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...

## Check OCR performance metrics

In [20]:
data

{'Upload_ID': 'AJ-20251113-153009-56ab04c4',
 'Extracted_AT': '2025-11-13T15:30:09.130996',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12k',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'}

In [21]:
from ocr_metrics import calculate_ocr_metrics

ocr_output = {'Upload_ID': 'AJ-20251113-140335-f9756256',
 'Extracted_AT': '2025-11-13T14:03:35.221558',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12k',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'
 }

ground_truth= {'Upload_ID': 'AJ-20251113-140335-f9756256',
 'Extracted_AT': '2025-11-13T14:03:35.221558',
 'Aircraft_Model': 'Airbus A320',
 'Registration_Number': '9M-XX1',
 'Departure_Airport': 'KUL',
 'Arrival_Airport': 'SIN',
 'Crew': 4,
 'Fuel': '12000',
 'Load': 150,
 'Defect_Message': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.'
 }

In [22]:
ocr_metrics_result = calculate_ocr_metrics(ocr_output, ground_truth)
ocr_metrics_result

[{'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Aircraft_Model',
  'Ground_Truth': 'Airbus A320',
  'OCR_Output': 'Airbus A320',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Registration_Number',
  'Ground_Truth': '9M-XX1',
  'OCR_Output': '9M-XX1',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Departure_Airport',
  'Ground_Truth': 'KUL',
  'OCR_Output': 'KUL',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Arrival_Airport',
  'Ground_Truth': 'SIN',
  'OCR_Output': 'SIN',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Crew',
  'Ground_Truth': '4',
  'OCR_Output': '4',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Fuel',
  'Ground_Truth': '12000',
  'OCR_Output': '12k',
  'Correct': 0.0,
  'Levenshtein': 3,
  'CER': 0.6,
  'WER': 1.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Load',
  'Ground_Truth': '150',
  'OCR_Output': '150',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0},
 {'Upload_ID': 'AJ-20251113-140335-f9756256',
  'Field': 'Defect_Message',
  'Ground_Truth': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.',
  'OCR_Output': 'WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.',
  'Correct': 1.0,
  'Levenshtein': 0,
  'CER': 0.0,
  'WER': 0.0}]

In [23]:
display(type(ocr_metrics_result))

list

result [class] -> results.model_dump() [dict] ->  json.dumps(result)[str]

In [24]:
# Can convert list to DataFrame directly -> but cannot be queried easily if saved as json, but CSV is OK
pd.DataFrame(ocr_metrics_result)

,Upload_ID,Field,Ground_Truth,OCR_Output,Correct,Levenshtein,CER,WER
0,AJ-20251113-140335-f9756256,Aircraft_Model,Airbus A320,Airbus A320,1.0,0,0.0,0.0
1,AJ-20251113-140335-f9756256,Registration_Number,9M-XX1,9M-XX1,1.0,0,0.0,0.0
2,AJ-20251113-140335-f9756256,Departure_Airport,KUL,KUL,1.0,0,0.0,0.0
3,AJ-20251113-140335-f9756256,Arrival_Airport,SIN,SIN,1.0,0,0.0,0.0
4,AJ-20251113-140335-f9756256,Crew,4,4,1.0,0,0.0,0.0
5,AJ-20251113-140335-f9756256,Fuel,12000,12k,0.0,3,0.6,1.0
6,AJ-20251113-140335-f9756256,Load,150,150,1.0,0,0.0,0.0
7,AJ-20251113-140335-f9756256,Defect_Message,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...,1.0,0,0.0,0.0

In [25]:
# convert list to json string [{}] -> cannot convert list to DataFrame directly
json.dumps(ocr_metrics_result)

'[{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Aircraft_Model", "Ground_Truth": "Airbus A320", "OCR_Output": "Airbus A320", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Registration_Number", "Ground_Truth": "9M-XX1", "OCR_Output": "9M-XX1", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Departure_Airport", "Ground_Truth": "KUL", "OCR_Output": "KUL", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Arrival_Airport", "Ground_Truth": "SIN", "OCR_Output": "SIN", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Crew", "Ground_Truth": "4", "OCR_Output": "4", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Fuel", "Ground_Truth": "12000", "OCR_Output": "12k", "Correct": 0.0, "Levenshtein": 3, "CER": 0.6, "WER": 1.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Load", "Ground_Truth": "150", "OCR_Output": "150", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}, {"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Defect_Message", "Ground_Truth": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.", "OCR_Output": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}]'

In [26]:
all_results = []
for ocr, gt in [(ocr_output, ground_truth)]:  # Add more pairs here
    all_results.extend(calculate_ocr_metrics(ocr, gt))

In [ ]:
# convert from list dict to JSON string {}
# For result to be queried easily, save as CSV/PARQUET, JSON will require SerDE transformation
all_results

In [94]:
"\n\n".join(json.dumps(data) for data in ocr_metrics_result)

'{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Aircraft_Model", "Ground_Truth": "Airbus A320", "OCR_Output": "Airbus A320", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Registration_Number", "Ground_Truth": "9M-XX1", "OCR_Output": "9M-XX1", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Departure_Airport", "Ground_Truth": "KUL", "OCR_Output": "KUL", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Arrival_Airport", "Ground_Truth": "SIN", "OCR_Output": "SIN", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Crew", "Ground_Truth": "4", "OCR_Output": "4", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Fuel", "Ground_Truth": "12000", "OCR_Output": "12k", "Correct": 0.0, "Levenshtein": 3, "CER": 0.6, "WER": 1.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Load", "Ground_Truth": "150", "OCR_Output": "150", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}\n\n{"Upload_ID": "AJ-20251113-140335-f9756256", "Field": "Defect_Message", "Ground_Truth": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.", "OCR_Output": "WAT POWL DS 244161 AND DS 244162 AL USS THAN CONTROL AND AC USS THAN PD ON POWL UT TO BE UNVOLVER A PROMIVE.", "Correct": 1.0, "Levenshtein": 0, "CER": 0.0, "WER": 0.0}'

In [ ]:
# Convert DataFrame to CSV string in memory
csv_buffer = StringIO()
df.to_csv(csv_buffer, index=False) # Set index=False to exclude the DataFrame index

# Create an S3 client
s3_client = boto3.client('s3')

# Upload the CSV string to S3
s3_client.put_object(Bucket=bucket_name, Key=s3_object_key, Body=csv_buffer.getvalue())

In [30]:

pd.DataFrame(ocr_metrics_result).Upload_ID.unique()

array(['AJ-20251113-140335-f9756256'], dtype=object)

In [31]:
from aws_utils import upload_dataframe_to_s3_folder

upload_dataframe_to_s3_folder(pd.DataFrame(ocr_metrics_result), folder_prefix=RESULTS_PREFIX, filename=f"AJ-20251113-140335-f9756256.csv")

/Users/jusnaini/Documents/MyProject/PERSONAL/ADE_interview/libenv/lib/python3.9/site-packages/boto3/compat.py:84: PythonDeprecationWarning: Boto3 will no longer support Python 3.9 starting April 29, 2026. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.10 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

's3://aircraftform-extractor-bucket/ocr_metrics/resultsAJ-20251113-140335-f9756256.csv'

In [95]:
from io import StringIO
csv_buffer = StringIO()
df_result = pd.DataFrame(ocr_metrics_result)
df_result.(csv_buffer, index=False) 
s3_client.put_object(Bucket=bucket_name, Key=s3_object_key, Body=csv_buffer.getvalue())

,Upload_ID,Field,Ground_Truth,OCR_Output,Correct,Levenshtein,CER,WER
0,AJ-20251113-140335-f9756256,Aircraft_Model,Airbus A320,Airbus A320,1.0,0,0.0,0.0
1,AJ-20251113-140335-f9756256,Registration_Number,9M-XX1,9M-XX1,1.0,0,0.0,0.0
2,AJ-20251113-140335-f9756256,Departure_Airport,KUL,KUL,1.0,0,0.0,0.0
3,AJ-20251113-140335-f9756256,Arrival_Airport,SIN,SIN,1.0,0,0.0,0.0
4,AJ-20251113-140335-f9756256,Crew,4,4,1.0,0,0.0,0.0
5,AJ-20251113-140335-f9756256,Fuel,12000,12k,0.0,3,0.6,1.0
6,AJ-20251113-140335-f9756256,Load,150,150,1.0,0,0.0,0.0
7,AJ-20251113-140335-f9756256,Defect_Message,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...,WAT POWL DS 244161 AND DS 244162 AL USS THAN C...,1.0,0,0.0,0.0